/* eslint-disable no-unused-vars */
const CATALOG = {
  brand: 'Nethraflix',

  profile: {
    name: 'Nethra',
    avatar: 'images/profile.jpg',
  },

  lockedProfile: {
    name: 'Aarav',
    avatar: 'images/aarav.jpg',
  },

  hero: {
    showId: 'us-the-series',
    tagline: 'Happy 19th birthday. Six months in, and you\'re already my favorite story.',
    meta: '6 Months, Romance, ★★★★★',
  },

  rows: [
    {
      id: 'our-story',
      title: 'Our Story',
      shows: ['us-the-series', 'first-adventures'],
    },
    {
      id: 'favorites',
      title: 'My Favorite Photos of You',
      shows: ['that-smile', 'facetime-favorites'],
    },
    {
      id: 'for-you',
      title: 'For You',
      shows: ['letter'],
    },
  ],

  shows: {
    'us-the-series': {
      id: 'us-the-series',
      title: 'Us: The Series',
      meta: 'Limited Series, Romance, ★★★★★, 4 Episodes',
      synopsis: 'Six months of us. Every moment worth replaying.',
      intro: 'Chikki, this is us. Six months in and I still cannot believe I get to call you mine.',
      poster: 'images/shows/us/01.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/us/01.jpg' },
        { image: 'images/shows/us/02.jpg' },
        { image: 'images/shows/us/03.jpg' },
        { image: 'images/shows/us/04.jpg' },
      ],
    },
    'first-adventures': {
      id: 'first-adventures',
      title: 'Our Places',
      meta: 'Adventure, Romance, ★★★★★, 23 Episodes',
      synopsis: 'Every dumb date, dorm night, and random adventure we had together.',
      intro: 'Okay chikki, every place we went was better because you were there. Sit back and watch our whole story.',
      poster: 'images/shows/places/06.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/places/01.jpg' },
        { image: 'images/shows/places/02.jpg' },
        { image: 'images/shows/places/03.jpg' },
        { image: 'images/shows/places/04.jpg' },
        { image: 'images/shows/places/05.jpg' },
        { image: 'images/shows/places/06.jpg' },
        { image: 'images/shows/places/07.jpg' },
        { image: 'images/shows/places/08.jpg' },
        { image: 'images/shows/places/09.jpg' },
        { image: 'images/shows/places/10.jpg' },
        { image: 'images/shows/places/11.jpg' },
        { image: 'images/shows/places/12.jpg' },
        { image: 'images/shows/places/13.jpg' },
        { image: 'images/shows/places/14.jpg' },
        { image: 'images/shows/places/15.jpg' },
        { image: 'images/shows/places/16.jpg' },
        { image: 'images/shows/places/17.jpg' },
        { image: 'images/shows/places/18.jpg' },
        { image: 'images/shows/places/19.jpg' },
        { image: 'images/shows/places/20.jpg' },
        { image: 'images/shows/places/21.jpg' },
        { image: 'images/shows/places/22.jpg' },
        { image: 'images/shows/places/23.jpg' },
      ],
    },
    'that-smile': {
      id: 'that-smile',
      title: 'That Smile',
      meta: 'Portrait, ★★★★★, 8 Episodes',
      synopsis: 'The one that stops me mid-sentence every time.',
      intro: 'Chikki, I had to make a whole show about your smile. It genuinely ruins my whole day in the best way.',
      poster: 'images/shows/smile/02.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/smile/01.jpg' },
        { image: 'images/shows/smile/02.jpg' },
        { image: 'images/shows/smile/03.jpg' },
        { image: 'images/shows/smile/04.jpg' },
        { image: 'images/shows/smile/05.jpg' },
        { image: 'images/shows/smile/06.jpg' },
        { image: 'images/shows/smile/07.jpg' },
        { image: 'images/shows/smile/08.jpg' },
      ],
    },
    'facetime-favorites': {
      id: 'facetime-favorites',
      title: 'My FaceTime Baby',
      meta: 'FaceTime, Romance, ★★★★★, 13 Episodes',
      synopsis: 'Every screenshot of you from our calls that I refused to delete.',
      intro: 'All my favorite FaceTime screenshots of you. Yes I saved every single one. No I am not sorry.',
      poster: 'images/shows/facetime/01.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/facetime/01.jpg' },
        { image: 'images/shows/facetime/02.jpg' },
        { image: 'images/shows/facetime/03.jpg' },
        { image: 'images/shows/facetime/04.jpg' },
        { image: 'images/shows/facetime/05.jpg' },
        { image: 'images/shows/facetime/06.jpg' },
        { image: 'images/shows/facetime/07.jpg' },
        { image: 'images/shows/facetime/08.jpg' },
        { image: 'images/shows/facetime/09.jpg' },
        { image: 'images/shows/facetime/10.jpg' },
        { image: 'images/shows/facetime/11.jpg' },
        { image: 'images/shows/facetime/12.jpg' },
        { image: 'images/shows/facetime/13.jpg' },
      ],
    },
    letter: {
      id: 'letter',
      title: 'A Letter For You',
      meta: 'Special, ★★★★★',
      synopsis: 'Open this one last. I wrote it for today.',
      poster: 'images/letter-cover.jpg',
      isLetter: true,
      wide: true,
      scenes: [],
    },
  },

  letter: {
    title: 'For Nethra, on your 19th',
    body: [
      'Nethra,',
      '',
      'I made you this little Netflix because you\'re the only thing I ever want to binge. Every moment, every memory, every version of you.',
      '',
      'Six months in, and I already feel like the luckiest person alive. Nineteen looks incredible on you.',
      '',
      'Thank you for the laughs, the late nights, the patience, and for being exactly who you are.',
      '',
      'Happy birthday. I love you more than any caption on this site could say.',
    ],
  },

  loader: {
    messages: [
      'Gathering your cutest memories...',
      'Sprinkling a little magic...',
      'Getting everything just right...',
      'Almost ready for you, Nethra...',
    ],
    welcome: 'Welcome to Nethraflix ♥',
  },

  geese: {
    hint: 'Psst — little gooses are floating around. Tap one!',
    facts: [
      'Did you know geese mate for life? Kind of like us, if you ask me.',
      'Did you know a baby goose is called a gosling?',
      'Did you know geese fly in a V so the whole flock has an easier time?',
      'Did you know a group of geese on the ground is called a gaggle?',
      'Did you know geese can live up to 25 years?',
      'Did you know geese have been domesticated for over 4,000 years?',
      'Did you know geese sometimes sleep with one eye open?',
      'Did you know male geese are called ganders?',
      'Did you know geese are surprisingly good guard animals?',
      'Did you know I put little gooses on this site because you love them?',
      'Did you know you are the only person I would build a whole Netflix for?',
      'Did you know your smile is literally my favorite view?',
      'Did you know I save every FaceTime screenshot of you? Every single one.',
      'Did you know six months with you already feels like the best plot twist ever?',
      'Did you know chikki is my favorite nickname in the entire universe?',
      'Did you know I think about you even when I am pretending to be productive?',
    ],
  },
};
