/* eslint-disable no-unused-vars */
const CATALOG = {
  brand: 'Nethraflix',

  profile: {
    name: 'Nethra',
    avatar: 'images/profile.jpg',
  },

  lockedProfile: {
    name: 'Aarav',
    avatar: 'images/aarav.jpg',
  },

  hero: {
    showId: 'us-the-series',
    tagline: 'Happy 19th birthday. Six months in, and you\'re already my favorite story.',
    meta: '6 Months, Romance, ★★★★★',
  },

  rows: [
    {
      id: 'our-story',
      title: 'Our Story',
      shows: ['us-the-series', 'first-adventures'],
    },
    {
      id: 'favorites',
      title: 'My Favorite Photos of You',
      shows: ['that-smile', 'facetime-favorites'],
    },
    {
      id: 'for-you',
      title: 'For You',
      shows: ['letter'],
    },
  ],

  shows: {
    'us-the-series': {
      id: 'us-the-series',
      title: 'Us: The Series',
      meta: 'Limited Series, Romance, ★★★★★, 4 Episodes',
      synopsis: 'Six months of us. Every moment worth replaying.',
      intro: 'Chikki, this is us. Six months in and I still cannot believe I get to call you mine.',
      poster: 'images/shows/us/01.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/us/01.jpg' },
        { image: 'images/shows/us/02.jpg' },
        { image: 'images/shows/us/03.jpg' },
        { image: 'images/shows/us/04.jpg' },
      ],
    },
    'first-adventures': {
      id: 'first-adventures',
      title: 'Our Places',
      meta: 'Adventure, Romance, ★★★★★, 23 Episodes',
      synopsis: 'Every dumb date, dorm night, and random adventure we had together.',
      intro: 'Okay chikki, every place we went was better because you were there. Sit back and watch our whole story.',
      poster: 'images/shows/places/06.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/places/01.jpg' },
        { image: 'images/shows/places/02.jpg' },
        { image: 'images/shows/places/03.jpg' },
        { image: 'images/shows/places/04.jpg' },
        { image: 'images/shows/places/05.jpg' },
        { image: 'images/shows/places/06.jpg' },
        { image: 'images/shows/places/07.jpg' },
        { image: 'images/shows/places/08.jpg' },
        { image: 'images/shows/places/09.jpg' },
        { image: 'images/shows/places/10.jpg' },
        { image: 'images/shows/places/11.jpg' },
        { image: 'images/shows/places/12.jpg' },
        { image: 'images/shows/places/13.jpg' },
        { image: 'images/shows/places/14.jpg' },
        { image: 'images/shows/places/15.jpg' },
        { image: 'images/shows/places/16.jpg' },
        { image: 'images/shows/places/17.jpg' },
        { image: 'images/shows/places/18.jpg' },
        { image: 'images/shows/places/19.jpg' },
        { image: 'images/shows/places/20.jpg' },
        { image: 'images/shows/places/21.jpg' },
        { image: 'images/shows/places/22.jpg' },
        { image: 'images/shows/places/23.jpg' },
      ],
    },
    'that-smile': {
      id: 'that-smile',
      title: 'That Smile',
      meta: 'Portrait, ★★★★★, 8 Episodes',
      synopsis: 'The one that stops me mid-sentence every time.',
      intro: 'Chikki, I had to make a whole show about your smile. It genuinely ruins my whole day in the best way.',
      poster: 'images/shows/smile/02.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/smile/01.jpg' },
        { image: 'images/shows/smile/02.jpg' },
        { image: 'images/shows/smile/03.jpg' },
        { image: 'images/shows/smile/04.jpg' },
        { image: 'images/shows/smile/05.jpg' },
        { image: 'images/shows/smile/06.jpg' },
        { image: 'images/shows/smile/07.jpg' },
        { image: 'images/shows/smile/08.jpg' },
      ],
    },
    'facetime-favorites': {
      id: 'facetime-favorites',
      title: 'My FaceTime Baby',
      meta: 'FaceTime, Romance, ★★★★★, 13 Episodes',
      synopsis: 'Every screenshot of you from our calls that I refused to delete.',
      intro: 'All my favorite FaceTime screenshots of you. Yes I saved every single one. No I am not sorry.',
      poster: 'images/shows/facetime/01.jpg',
      fit: 'contain',
      loop: false,
      scenes: [
        { image: 'images/shows/facetime/01.jpg' },
        { image: 'images/shows/facetime/02.jpg' },
        { image: 'images/shows/facetime/03.jpg' },
        { image: 'images/shows/facetime/04.jpg' },
        { image: 'images/shows/facetime/05.jpg' },
        { image: 'images/shows/facetime/06.jpg' },
        { image: 'images/shows/facetime/07.jpg' },
        { image: 'images/shows/facetime/08.jpg' },
        { image: 'images/shows/facetime/09.jpg' },
        { image: 'images/shows/facetime/10.jpg' },
        { image: 'images/shows/facetime/11.jpg' },
        { image: 'images/shows/facetime/12.jpg' },
        { image: 'images/shows/facetime/13.jpg' },
      ],
    },
    letter: {
      id: 'letter',
      title: 'A Letter For You',
      meta: 'Special, ★★★★★',
      synopsis: 'Open this one last. I wrote it for today.',
      poster: 'images/letter-cover.jpg',
      isLetter: true,
      wide: true,
      scenes: [],
    },
  },

  letter: {
    title: 'For Chikki',
    body: `happy birthday love. All week this week you've been saying oh its just another day or oh its not that important blah blah blah well guess what you're wrong and i'm right so now suck it up. Your birthday isn't just another day to me, it's one of the most important days to me because today gave me my person, the most wonderful person I've ever met my entire life. I've only known you 11 months but these 11 months have been the best of my life. I know that the people around you, your friends, your family, me, i know you've made all of our lives better just by being here. There'll be days where you don't think so, there'll be days where you doubt yourself but I want you to know that I am always proud of you and Chikki you are the biggest blessing in my life, you are every wish I've ever made and will ever make, every 11:11, every birthday candle, every eyelash, love it's always been you.

I hope you have the best birthday, I love you with all my heart, you are my world and baby,

i miss you
i love you
Happy birthday chikki.`,
    signoff: 'Aarav ♥',
  },

  loader: {
    messages: [
      'Gathering your cutest memories...',
      'Sprinkling a little magic...',
      'Getting everything just right...',
      'Almost ready for you, Nethra...',
    ],
    welcome: 'Welcome to Nethraflix ♥',
  },

  geese: {
    hint: 'Psst — little gooses are floating around. Tap one!',
    facts: [
      'Did you know geese mate for life? Kind of like us, if you ask me.',
      'Did you know a baby goose is called a gosling?',
      'Did you know geese fly in a V so the whole flock has an easier time?',
      'Did you know a group of geese on the ground is called a gaggle?',
      'Did you know geese in the air are called a skein?',
      'Did you know geese can live up to 25 years?',
      'Did you know geese have been domesticated for over 4,000 years?',
      'Did you know geese sometimes sleep with one eye open?',
      'Did you know male geese are called ganders?',
      'Did you know geese are surprisingly good guard animals?',
      'Did you know geese have teeth on their tongues? Weird but true.',
      'Did you know geese can fly over Mount Everest?',
      'Did you know geese remember faces and will absolutely hold a grudge?',
      'Did you know a goose honk can be heard from a mile away?',
      'Did you know geese molt all their flight feathers at once and cannot fly for a bit?',
      'Did you know geese poop like every eight minutes? Sorry.',
      'Did you know baby geese imprint on the first thing they see?',
      'Did you know Egyptians kept geese as pets way back in the day?',
      'Did you know a goose chased me at a park once and I still think about it?',
      'Did you know geese are basically loud dinosaurs with better outfits?',
      'Did you know I put gooses on this site because you love them?',
      'Did you know I made you a whole website instead of a normal birthday card?',
      'Did you know I still laugh at that Atomic Wings photo of you?',
      'Did you know I save every FaceTime screenshot of you? Every single one.',
      'Did you know you take forever to pick food and I do not even mind?',
      'Did you know chikki is the only nickname that sounds right in my head?',
      'Did you know I re-read our texts before bed sometimes?',
      'Did you know your half-asleep FaceTime face is still cute?',
      'Did you know I told my friends about you again this week?',
      'Did you know ice skating with you was way more fun than I expected?',
      'Did you know you do that nose scrunch thing when you laugh and it gets me every time?',
      'Did you know six months with you went by way too fast?',
      'Did you know I already know what I am getting you next and it is a secret?',
      'Did you know you are the reason I keep checking my phone like an idiot?',
      'Did you know I would sit through any mall trip if you are there?',
      'Did you know your smile is unfair? Like actually unfair.',
      'Did you know Nethraflix only has one viewer and it is you?',
      'Did you know I fall asleep thinking about our dumb little inside jokes?',
      'Did you know you are my favorite person to do absolutely nothing with?',
    ],
  },
};
